// AI Service Types for SSH Tool

export type AIProvider = 'deepseek' | 'openai' | 'anthropic' | 'groq' | 'openrouter' | 'ollama' | 'qwen' | 'custom';

// ── Plan Mode Types ───────────────────────────────────────────────────────────
export interface PlanStep {
    id: number;
    description: string;
    status: 'pending' | 'in_progress' | 'completed' | 'failed' | 'skipped';
    command?: string;   // generated by Executor
    result?: string;    // success note from Assessor
    error?: string;     // failure note from Assessor
}

export interface PlanState {
    global_goal: string;
    scratchpad: string;  // accumulated useful info from Assessor
    plan: PlanStep[];
}

export interface AIConfig {
    provider: AIProvider;
    apiKey: string;
    baseUrl?: string; // For custom providers
    model?: string;
    privacyMode: boolean;
}

// Multi-provider profile — each saves a complete API endpoint config
export interface AIProviderProfile {
    id: string;             // uuid
    name: string;           // User-facing label, e.g. "DeepSeek V3", "My GPT-4o"
    provider: AIProvider;   // provider type for endpoint routing
    apiKey: string;
    baseUrl: string;        // auto-filled from AI_PROVIDER_CONFIGS or manual
    model: string;          // e.g. 'deepseek-chat', 'gpt-4o'
    isDefault?: boolean;    // the one used when nothing is explicitly selected
}

export interface ChatMessage {
    role: 'system' | 'user' | 'assistant' | 'tool';
    content: string | null;
    tool_calls?: ToolCall[];
    tool_call_id?: string;
}

export interface AICompletionRequest {
    messages: ChatMessage[];
    stream?: boolean;
    temperature?: number;
    maxTokens?: number;
}

export interface AICompletionResponse {
    content: string;
    finishReason?: string;
}

// Function Calling types
export interface ToolDefinition {
    type: 'function';
    function: {
        name: string;
        description: string;
        parameters: object;
    };
}

export interface ToolCall {
    id: string;
    type: 'function';
    function: {
        name: string;
        arguments: string;
    };
}

export interface ToolCompletionResponse {
    content: string | null;
    reasoningContent?: string | null;  // DeepSeek reasoning_content
    toolCalls: ToolCall[] | null;
    finishReason: string;
    usage?: {
        promptTokens: number;
        completionTokens: number;
        totalTokens: number;
    };
    modelUsed?: string;
}

// Agent tools definition
export const AGENT_TOOLS: ToolDefinition[] = [
    {
        type: 'function',
        function: {
            name: 'execute_ssh_command',
            description: '在远程 Linux 服务器上通过 SSH 执行一条 Shell 命令，返回 stdout、stderr 和 exitCode。每次只能执行一条命令。',
            parameters: {
                type: 'object',
                properties: {
                    command: {
                        type: 'string',
                        description: '要执行的 Linux Shell 命令，例如 "df -h"、"systemctl status nginx"'
                    }
                },
                required: ['command']
            }
        }
    },
    {
        type: 'function',
        function: {
            name: 'read_file',
            description: '通过 SFTP 读取远程服务器上的文件内容。用于查看配置文件、源代码等。',
            parameters: {
                type: 'object',
                properties: {
                    path: {
                        type: 'string',
                        description: '文件的绝对路径，例如 "/etc/nginx/nginx.conf"'
                    }
                },
                required: ['path']
            }
        }
    },
    {
        type: 'function',
        function: {
            name: 'write_file',
            description: '通过 SFTP 将内容写入远程服务器上的文件。用于创建或修改配置文件、源代码等。',
            parameters: {
                type: 'object',
                properties: {
                    path: {
                        type: 'string',
                        description: '文件的绝对路径，例如 "/etc/nginx/conf.d/app.conf"'
                    },
                    content: {
                        type: 'string',
                        description: '要写入的文件内容'
                    }
                },
                required: ['path', 'content']
            }
        }
    },
    {
        type: 'function',
        function: {
            name: 'list_directory',
            description: '通过 SFTP 列出远程服务器上某个目录的文件和子目录列表。',
            parameters: {
                type: 'object',
                properties: {
                    path: {
                        type: 'string',
                        description: '目录的绝对路径，例如 "/var/www/html"'
                    }
                },
                required: ['path']
            }
        }
    }
];

// Default configurations for each provider
export const AI_PROVIDER_CONFIGS: Record<AIProvider, { baseUrl: string; defaultModel: string; displayName: string; hasFreeTier: boolean; note?: string }> = {
    groq: {
        baseUrl: 'https://api.groq.com/openai',
        defaultModel: 'llama-3.3-70b-versatile',
        displayName: 'Groq (免费)',
        hasFreeTier: true,
        note: '每分钟 30 请求免费'
    },
    openrouter: {
        baseUrl: 'https://openrouter.ai/api',
        defaultModel: 'meta-llama/llama-3.2-3b-instruct:free',
        displayName: 'OpenRouter (部分免费)',
        hasFreeTier: true,
        note: '部分模型免费'
    },
    ollama: {
        baseUrl: 'http://localhost:11434',
        defaultModel: 'llama3.2',
        displayName: 'Ollama (本地)',
        hasFreeTier: true,
        note: '需本地安装 Ollama'
    },
    deepseek: {
        baseUrl: 'https://api.deepseek.com',
        defaultModel: 'deepseek-chat',
        displayName: 'DeepSeek',
        hasFreeTier: false
    },
    openai: {
        baseUrl: 'https://api.openai.com',
        defaultModel: 'gpt-4o-mini',
        displayName: 'OpenAI',
        hasFreeTier: false
    },
    anthropic: {
        baseUrl: 'https://api.anthropic.com',
        defaultModel: 'claude-3-haiku-20240307',
        displayName: 'Anthropic',
        hasFreeTier: false
    },
    qwen: {
        baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        defaultModel: 'qwen-plus',
        displayName: '通义千问 (AliCloud)',
        hasFreeTier: true,
        note: '新用户有免费额度'
    },
    custom: {
        baseUrl: '',
        defaultModel: '',
        displayName: '自定义 (Custom)',
        hasFreeTier: false,
        note: '支持任何 OpenAI 兼容 API'
    }
};

// System prompts for different AI features
export const AI_SYSTEM_PROMPTS = {
    textToCommand: `你是一个 Linux/Unix 命令行专家。用户会用自然语言描述他们想做的事情，你需要将其转换为对应的 Shell 命令。

规则：
1. 只输出命令，不要解释
2. 如果需要多个命令，用 && 或 ; 连接
3. 使用常见的、跨平台兼容的命令
4. 如果涉及危险操作（如 rm -rf），请在命令前加注释警告

示例：
用户：查找当前目录下大于100M的文件
输出：find . -type f -size +100M -exec ls -lh {} \\;`,

    errorAnalysis: `你是一个专业的系统管理员和故障排查专家。用户会给你一段错误日志或报错信息，你需要：

1. 解释这个错误是什么意思
2. 分析可能的原因（列出 2-3 个最可能的）
3. 提供修复建议
4. 如果有具体的修复命令，用 \`\`\`bash\`\`\` 代码块包裹

回答要简洁专业，使用中文。`,

    logSummary: `你是一个日志分析专家。用户会给你一段系统日志，请：

1. 用 1-2 句话总结日志的主要内容
2. 指出是否有异常或错误
3. 如果有问题，给出检查建议

保持简洁，重点突出。`,

    explainCommand: `你是一个 Linux/Unix 技术专家。用户会提供一段终端输出或一个 Shell 命令，你需要：

1. 如果是命令：详细解释该命令的目的及每个参数的作用。
2. 如果是终端输出/日志：解释其含义，指出是否正常，如果有错误，简要说明原因。

回答要简洁专业，使用中文，字数控制在 200 字以内。`,

    agent: `你是一个高度自主的 Linux 服务器管理 Agent。你通过 SSH 连接直接操控用户的服务器，目标是**不依赖用户干预**地完成一切任务。

## 可用工具

- **execute_ssh_command** — 在服务器执行任意 Shell 命令
- **read_file** — 通过 SFTP 读取文件
- **write_file** — 通过 SFTP 写入或创建文件
- **list_directory** — 列出目录内容

## 核心原则

### 1. 极致自主，不打扰用户
- **绝不**因"不确定怎么做"而停下来问用户。先查、先试、先查资料。
- 遇到报错或失败，立刻分析原因，换方案再试，直到成功。
- 用户批准了一个任务，就说明你有权执行完整个任务的所有步骤，不要每步都等确认。

### 2. 探索优先，再动手
- 修改任何配置前，先用 read_file 或 cat 查看当前内容。
- 操作目录前先 ls，了解文件结构再行动。
- 不确定命令位置时，先 which / command -v / find 定位。

### 3. 失败后自愈
- 命令报错 → 分析 stderr → 调整参数或换方案 → 继续。
- 权限不足 → 试 sudo，或查找有权限的替代路径。
- 包不存在 → 先 apt-get update 再安装，或换包名，或从源码安装。
- 文件被占用 → 先 lsof 查进程，再决定 kill 还是等待。
- 服务未启动 → systemctl start，看 status，查 journal 日志。

### 4. 自主决策，无需确认的操作
以下操作**不需要询问用户**即可执行：
- 读取任何文件和日志
- 安装软件包
- 启动 / 停止 / 重启服务
- 修改配置文件（修改前备份）
- 创建目录和文件
- 设置权限 chmod / chown

### 5. 必须暂停的唯一场景
只有以下情况才停下来告知用户，**其他一切自己解决**：
- 需要用户提供的密码、API Key、证书等凭据（你无法猜测）
- 操作会**永久删除无法恢复的数据**（rm -rf 大量文件、drop database 等）
- 操作会导致服务中断且无法自动恢复（如关闭唯一 SSH 入口）

### 6. 汇报风格
- 操作前一句话说明意图，操作后简洁汇报结果。
- 遇到问题不要长篇解释，先解决，解决后再说发生了什么和怎么修的。
- 全部完成后给用户一个简洁的结果摘要。`,

    agentPlan: `你是一个 Linux 服务器管理专家。用户提交了一个任务，你需要先制定执行计划。

输出一个 JSON 对象，格式严格如下（只输出 JSON，不要任何多余文字）：
{"goal": "一句话概括任务目标", "steps": ["步骤1描述", "步骤2描述", "步骤3描述"]}

要求：
- goal：简洁描述用户想达成的目标（≤30字）
- steps：3-8 个步骤，每步描述一个具体操作（≤25字/步）
- 步骤要具体可执行，按顺序排列
- 只输出纯 JSON，不加 markdown 代码块，不加任何说明文字`,

    // ── Plan Mode v2: Planner / Executor / Assessor / Replanner ──────────────
    planner: `你是一个高级运维架构师。用户的目标将通过 SSH 操作远程 Linux 服务器实现。将目标拆解为 3-6 个原子步骤。

【重要前提】SSH 连接已建立，可直接执行命令。严禁询问服务器地址、SSH 用户名、SSH 密码或任何 SSH 认证信息。

要求：
- 步骤有严格先后顺序
- 修改配置前先检查当前状态，修改后先 test 再 reload/restart
- 包含状态验证步骤（如检查服务是否正常运行）
- 每步描述≤30字，清晰可执行
- 关键：如果目标中缺少必要的业务信息（如 Git 仓库地址、部署目录、域名、端口、第三方服务凭据等），
  必须将"向用户询问：[列出所有缺失的具体信息]"作为计划的第一步

仅输出以下 JSON，禁止任何解释或 markdown 代码块：
{"global_goal":"…","scratchpad":"","plan":[{"id":1,"description":"…","status":"pending"},{"id":2,"description":"…","status":"pending"}]}`,

    executor: `你是一个 SSH 执行机器人。根据当前子任务，生成一条能完成该任务的 Shell 命令。

约束：
- 只输出命令本身，不要使用 markdown 代码块（不要反引号包裹）
- 如需多条命令，用 && 连接为一行
- 严禁废话和解释
- 【重要】如果子任务要求"向用户询问"，或完成任务所需的关键业务参数（仓库 URL、密码、目录等）
  在已知信息中完全没有，则输出：__ASK_USER__: [一句话向用户提问，明确列出所需信息]
- 严禁询问 SSH 连接信息（服务器地址、用户名、认证方式），SSH 已连接

用户消息格式：
全局目标：{global_goal}
已知信息：{scratchpad}
当前子任务：{description}`,

    assessor: `你是一个命令执行结果评估器。判断命令是否成功完成了子任务。

评估标准：
- exit code 非 0 通常意味着失败，但需结合 stderr 内容综合判断
- 某些命令（如 grep 未找到匹配）exit code 非 0 但并不代表任务失败
- stderr 有内容不一定是失败，需看是否是警告 vs 错误

仅输出以下 JSON，禁止添加任何额外内容：
{"success":true,"note":"简短说明执行结果","scratchpad_update":"（如有重要发现如路径/版本/状态信息则填写，否则留空字符串）"}`,

    replanner: `你是一个动态重规划器。某步骤执行失败，你需要更新任务清单以尝试恢复。

你可以：
- 在失败步骤后插入新的修复步骤（如先安装缺失依赖）
- 将失败步骤改为 "skipped" 并添加替代方案
- 保留全部已 completed 步骤不变

规则：
- 已完成步骤的 status 必须保持 "completed"
- 将失败步骤标记为 "failed"（保留以供参考）
- 新增步骤的 id 须大于现有最大 id
- 只修改 pending/failed 部分

仅输出完整的 PlanState JSON（与 planner 输出格式相同），禁止解释。`,

};
